### ISSUE TITLE
Error compiling C.impl

### ISSUE THREAD

**Issue by eddavis2** [knivd/C.impl#1]
Windows 10:

I tried to compile this, but I get:

cimpl.c:5:10: fatal error: ../xmem.h: No such file or directory
    5 | #include "../xmem.h"
      |          ^~~~~~~~~~~
compilation terminated.
opr.c:9:10: fatal error: ../xmem.h: No such file or directory
    9 | #include "../xmem.h"
      |          ^~~~~~~~~~~
compilation terminated.

And when I look, indeed, the file xmem.h does not exist.

I tried this from the command line, and also from the DevC++ environment.

**Comment by knivd** [comment]
Yes, indeed! I had forgotten to add the files in the main dir. Added now
There is a known issue in the xmem library when the amount of available memory is very low. This will be fixed soon
