### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by eddavis2** [knivd/C.impl#2]
Windows 10, Dev C++ v6.3:

Tried with the new files (thanks for the quick response!), and now I get:

In file included from ../../../ride/ride.h:35,
                 from ../../../ride/fos.h:8,
                 from ../diskio.c:15:
../../../ride/graphics.h:37:1: error: C++ style comments are not allowed in ISO C90
   37 | // font definition header
      | ^
compilation terminated due to -Wfatal-errors.

I changed the compiler option to use ISO C99 instead, and now I get:

../diskio.c: In function 'disk_initialize':
../diskio.c:109:37: error: macro "x_malloc" passed 2 arguments, but takes just 1
  109 |       x_malloc((byte **) &buff, 1024);
      |                                     ^
compilation terminated due to -Wfatal-errors.

**Comment by knivd** [comment]
Dev-C++ 6.3 is slightly different from its previous 5.xx version. In the project, tab "Compiler", tab "Output", there is an option "Do not assemble, but output assembler code (-S)" which is defaulting to "Yes". Change it to "No". This should be enough to compile the project directly from the downloaded zip

**Comment by eddavis2** [comment]
Hold the presses :) It looks like it compiled!
Thanks for the help!
I'll start playing with it!

**Comment by knivd** [comment]
Glad to see it compiled
